export const GETAPIDATA = 'GETAPIDATA';
export const SETAPIDATA = 'SETAPIDATA';
export const GETBESTSELLERSDATA = 'GETBESTSELLERSDATA';
export const SETBESTSELLERSDATA = 'SETBESTSELLERSDATA';
export const GETSPECIFICCATDATA = 'GETSPECIFICCATDATA';
export const SETSPECIFICCATDATA = 'SETSPECIFICCATDATA';
